services:
  genesis-generator:
    container_name: genesis-generator
    image: "hyperledger/besu:latest"
    volumes:
      - type: bind
        source: ./data
        target: /opt/besu/data
        read_only: false
      - type: bind
        source: ./configs
        target: /opt/besu/configs
        read_only: true
    command: [ "operator", "generate-blockchain-config", "--config-file=configs/networkConfig.json", "--to=data", "--private-key-file-name=key" ]
    entrypoint:
      - "besu"
  node:
    container_name: node
    image: "hyperledger/besu:latest"
    ports:
      - "30303:30303/udp"
      - "30303:30303/tcp"
      - "127.0.0.1:8545:8545"
      - "127.0.0.1:8551:8551"
    expose: ["8545", "8551", "30303"]
    volumes:
      - type: bind
        source: ./data/genesis.json
        target: /opt/besu/genesis.json
        read_only: true
      - type: bind
        source: ./configs/node.toml
        target: /opt/besu/configs/node.toml
        read_only: true
    command: [ "--config-file=configs/node.toml", "--p2p-host=211.226.71.14" ]
    entrypoint:
      - "besu"
  peer:
    container_name: peer1
    image: "hyperledger/besu:latest"
    command: [ "--config-file=configs/node.toml" ]
    entrypoint:
      - "besu"